import { decodeJwt, createRemoteJWKSet, type JWTVerifyGetKey } from "jose";
import { AUTH_ERROR_CODES, AuthError } from "@/lib/api/errors";
import type { AuthDataStore, EscolentUser } from "../dataStore";
import { verifyLtiLaunchJwt } from "./verifyLaunch";
import { parseLtiLaunchClaims } from "./claims";
import { LTI_CLAIM } from "./types";

export interface EstablishLtiSessionResult {
  user: EscolentUser;
  role: "student" | "teacher";
  tenantId: string;
  courseId: string;
}

export interface EstablishLtiSessionOptions {
  dataStore: AuthDataStore;
  idToken: string;
  /** Must match the nonce this session's /login step generated and stored. */
  expectedNonce: string;
  /** Injectable so tests can supply a local JWKS instead of fetching a real URL. */
  jwksResolver?: (jwksUrl: string) => JWTVerifyGetKey;
  /**
   * Resolves the Supabase Auth user id for a brand-new email (see
   * authAdmin.ts in production; tests pass a trivial id generator). Only
   * called when no `public.users` row exists yet for this email — see the
   * comment on UpsertUserInput.id for why the id has to come from here
   * rather than being generated by the data store itself.
   */
  resolveAuthUserId: (email: string) => Promise<string>;
}

function malformedTokenError(): AuthError {
  return new AuthError(
    AUTH_ERROR_CODES.INVALID_LTI_JWT,
    "Your LTI launch could not be verified — the sign-in request may have expired or been tampered with.",
    401,
  );
}

/**
 * The full LTI 1.3 launch → Escolent session pipeline (task 3.1). Peeks at
 * the token's (unverified) `iss` + deployment_id first to look up which
 * Platform/tenant this is — a chicken-and-egg step LTI requires, since the
 * key needed to verify the signature is itself looked up per-deployment —
 * then verifies signature/issuer/audience/nonce against that deployment's
 * registered config before trusting anything else in the token.
 */
export async function establishLtiSession(
  options: EstablishLtiSessionOptions,
): Promise<EstablishLtiSessionResult> {
  const { dataStore, idToken, expectedNonce } = options;

  let unverified: ReturnType<typeof decodeJwt>;
  try {
    unverified = decodeJwt(idToken);
  } catch {
    throw malformedTokenError();
  }

  const issuer = unverified.iss;
  const deploymentId = unverified[LTI_CLAIM.deploymentId];
  if (!issuer || typeof deploymentId !== "string" || deploymentId.length === 0) {
    throw malformedTokenError();
  }

  const lmsConfig = await dataStore.findLmsConfigByIssuerAndDeployment(issuer, deploymentId);
  if (!lmsConfig) {
    throw new AuthError(
      AUTH_ERROR_CODES.UNKNOWN_LMS_DEPLOYMENT,
      "This LMS deployment is not registered with Escolent.",
      401,
      { issuer, deploymentId },
    );
  }

  const jwks = options.jwksResolver
    ? options.jwksResolver(lmsConfig.jwksUrl)
    : createRemoteJWKSet(new URL(lmsConfig.jwksUrl));

  const payload = await verifyLtiLaunchJwt(idToken, {
    jwks,
    issuer,
    audience: lmsConfig.clientId,
    expectedNonce,
  });

  const claims = parseLtiLaunchClaims(payload);

  const existingUser = await dataStore.findUserByEmail(claims.email);
  const authUserId = existingUser?.id ?? (await options.resolveAuthUserId(claims.email));
  const user = await dataStore.upsertUser({
    id: authUserId,
    tenantId: lmsConfig.tenantId,
    email: claims.email,
    fullName: claims.fullName,
    lmsUserId: claims.subject,
  });
  await dataStore.assignRole(user.id, claims.role, lmsConfig.tenantId);

  return { user, role: claims.role, tenantId: lmsConfig.tenantId, courseId: claims.course.id };
}

export type { EscolentUser };
